yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      'typescript': '*'
  'graphql-config@*':
    peerDependencies:
      'typescript': '*'
  'eslint-plugin-graphql@*':
    peerDependencies:
      'typescript': '*'
  'gatsby@*':
    peerDependencies:
      'babel-eslint': '*'
      'typescript': '*'
  'react-dev-utils@*':
    peerDependencies:
      'typescript': '*'
      'webpack': '*'
